name: DisMineBridge
version: '0.2.2.1'
main: de.MaxBrassLoud.disMineBridge.DisMineBridge
api-version: '1.21'
authors: [ MaxBrassLoud ]
description: A simpe yet powerful moderaion Plugin for Minecraft 1.21.8


commands:
  whitelist:
    description: Verwalte die Server Whitelist
    usage: /whitelist <add|remove|on|off> [Spieler]
    permission: dmb.whitelist

  vanish:
    description: Bringt einen Moderator in einen Status den nur andere Moderatoren sehen und wird für restliche Spieler unsichtbar gemacht
    usage: /vanish
    permission: dmb.vanish

  ban:
    description: Kann einen Spieller vom Server ausschließen
    usage: /ban [Player] [Duration] [Reason]
    permission: dmb.ban

  unban:
    description: Kann einen Serverausschluss rückgängig machen
    usage: /unban [Player]
    permission: dmb.unban

  kick:
    description: Die Verbindung vom Server für einen Spieler trennen
    usage: /kick [Player] [Reason]
    permission: dmb.kick

  warn:
    description: Jemanden verwarnen
    usage: /warn [Player] [Reason]
    permission: dmb.warn

  punish:
    description: Jemanden bestrafen
    usage: /punish
    permission: dmb.punish

  punishment:
    description: Bestrafungen hinzufügen
    usage: /punishment
    permission: dmb.punishment

  mute:
    description: Mutet einen Spieler
    usage: /mute <Spieler> <Dauer> <Grund>
    permission: dmb.mute

  unmute:
    description: Entmutet einen Spieler
    usage: /unmute <Spieler> [Grund]
    permission: dmb.unmute



permissions:
  dmb.mute:
    description: Erlaubt das Muten von Spielern
    default: op

  dmb.unmute:
    description: Erlaubt das Entmuten von Spielern
    default: op

  dmb.punishment:
    description: Berechtigung für den /punishments command
    default: op

  dmb.punishment.add:
    description: Berechtigung eine Bestrafung hinzuzufügen
    default: op

  dmb.punishment.remove:
    description: Berechtigung Strafen zu entfernen
    default: op

  dmb.punishment.list:
    description: Berechtigung alle Strafen zu sehen
    default: op

  dmb.punishment.reload:
    description: Berechtigung Strafen neu zu laden
    default: op

  dmb.punishment.all:
    description: Alle Berechtigung alle Punishment Features zu nutzen
    default: op
    children:
      dmb.punishment.add: true
      dmb.punishment.remove: true
      dmb.punishment.list: true
      dmb.punishment.reload: true
      dmb.punishment: true


  dmb.punish:
    description: Berechtigung jemanden zu bestrafen
    default: op

  dmb.kick:
    description: Berechtigung jemanden vom server zu trennen
    default: op

  dmb.warn:
    description: Berechtigung jemanden zu verwarnen
    default: op

  dmb.whitelist:
    description: Erlaubt die Verwaltung der Whitelist
    default: op

  dmb.whitelist.bypass:
    description: Bypasses the Whitelist
    default: op

  dmb.whitelist.all:
    description: Alle Whitelist Features
    default: op
    children:
      dmb.whitelist: true
      dmb.whitelist.bypass: true

  dmb.vanish:
    description: Zugriff auf Vanish command
    default: op

  dmb.vanish.see:
    description: Lässt alle im Vanish sehen
    default: op

  dmb.vanish.others:
    description: Lässt andere in den Vanish status bringen
    default: op

  dmb.vanish.all:
    description: Alle Vanish Features
    default: op
    children:
      dmb.vanish: true
      dmb.vanish.see: true
      dmb.vanish.others: true

  dmb.ban:
    description: Berechtigung Spieler zu bannen
    default: op
  dmb.unban:
    description: Berechtigung einen Bann aufzuheben
    default: op

  dmb.ban.all:
    description: Alle Bann Aktionen Nutzen
    default: op
    children:
      dmb.ban: true
      dmb.unban: true

  dmb.admin:
    description: Voller Zugriff auf alle Plugin-Funktionen
    default: op
    children:
      dmb.whitelist.all: true
      dmb.vanish.all: true
      dmb.ban.all: true
      dmb.kick: true
      dmb.warn: true
      dmb.punishment.all: true
      dmb.mute: true
      dmb.unmute: true


