name: DisMineBridge
version: '0.1'
main: de.MaxBrassLoud.disMineBridge.DisMineBridge
api-version: '1.21'
authors: [ MaxBrassLoud ]
description: A simpe yet powerful moderaion Plugin for Minecraft 1.21.8


commands:
  whitelist:
    description: Verwalte die Server Whitelist
    usage: /whitelist <add|remove|on|off> [Spieler]
    permission: disminebridge.whitelist




permissions:
  disminebridge.whitelist:
    description: Erlaubt die Verwaltung der Whitelist
    default: op

  whitelist.bypass:
    description: Bypasses the Whitelist
    default: op

  disminebridge.admin:
    description: Voller Zugriff auf alle Plugin-Funktionen
    default: op
    children:
      disminebridge.whitelist: true

